---



tenantlist:

  - tenant: 'BLACK-COMMON'
  - tenant: 'BLACK-Prod'
  - tenant: 'BLACK-PreProd'
  - tenant: 'grey-COMMON'

vrflist:

  - tenant: 'BLACK-COMMON'
    vrf: 
      - 'BLACK-COMMON-vrf1'
      - 'BLACK-COMMON-vrf2'
      - 'BLACK-COMMON-vrf3'

bdlist:
    tenant: 'BLACK-COMMON'
    vrf: 'BLACK-COMMON-vrf1'
    bd:
      - 'BD01'
      - 'BD02'
      - 'BD03'
      - 'BD04'
      - 'BD05'
      - 'BD06'
      - 'BD07'
      - 'BD08'


ap: "intranet"
epgs:
  - epg: "web"
    encap: "21"
    contract_type: "both"
    consumer: "sql"
    provider: "web"
  - epg: "sql"
    encap: "22"
    contract_type: "provider"
    provider: "sql"
epg_contracts:
  - epg: "web"
    contract: "web"
    contract_type: "provider"
  - epg: "web"
    contract: "sql"
    contract_type: "consumer"
  - epg: "sql"
    contract: "sql"
    contract_type: "provider"
