---
- name: TOP LEVEL PLAY - CREATE ACI STUFF
  hosts: all
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE TENANT FILTERS EXIST
      tags: tfe
      aci_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        #action: "post"
        #protocol: "https"
        tenant: "{{ bdlist.tenant }}"
        filter: "{{ item }}"
        descr: "Filter Created Using Ansible"
      with_items:
        - "https"
        - "sql"

    - name: ENSURE FILTERS HAVE FILTER ENTRIES
      tags: ffe
      aci_filter_entry:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ bdlist.tenant }}"
        filter: "{{ item.filter }}"
        entry: "{{ item.entry }}"
        ether_type: "ip"
        ip_protocol: "tcp"
        dst_port_start: "{{ item.port }}"
        dst_port_end: "{{ item.port }}"
      with_items:
        - filter: "https"
          entry: "https"
          port: 443
        - filter: "sql"
          entry: "sql"
          port: 1433

    - name: ENSURE TENANT CONTRACTS EXIST
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ bdlist.tenant }}"
        contract: "{{ item }}"
        scope: "context"
        description: "Contract Created Using Ansible"
      with_items:
        - "web"
        - "sql"

    - name: ENSURE CONTRACTS HAVE CONTRACT SUBJECTS
      aci_contract_subject:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ bdlist.tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
      with_items:
        - contract: "web"
          subject: "https"
        - contract: "sql"
          subject: "sql"

    - name: ENSURE CONTRACTS SUBJECTS ARE ASSOCIATED WITH FILTERS
      aci_contract_subject_to_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant_name: "{{ bdlist.tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
        filter: "{{ item.filter }}"
      with_items:
        - contract: "web"
          subject: "https"
          filter: "https"
        - contract: "sql"
          subject: "sql"
          filter: "sql"

    - name: ENSURE APPLICATION EXISTS
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: false
        tenant: "{{ bdlist.tenant }}"
        ap: "{{ ap }}"
        descr: "App Profile Created Using Ansible"

    - name: ENSURE APPLICATION EPGS EXISTS
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ bdlist.tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        bd: "prod_bd"
        description: "EPG Created Using Ansible"
      with_items: "{{ epgs }}"


    - name: ENSURE DOMAIN IS BOUND TO EPG
      aci_epg_to_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: false
        tenant: "{{ bdlist.tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        domain: "aci_ansible_lab"
        domain_type: "vmm"
        vm_provider: "vmware"
        encap_mode: "auto"
        encap: "{{ item.encap }}"
      with_items: "{{ epgs }}"

    - name: ENSURE EPG IS ASSOCIATED TO CONTRACTS
      aci_epg_to_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ bdlist.tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        contract: "{{ item.contract }}"
        contract_type: "{{ item.contract_type }}"
      with_items: "{{ epg_contracts }}"