---
- name: TOP LEVEL PLAY - CREATE ACI STUFF
  hosts: apicProd
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE TENANT EXISTS
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ item.tenant }}"
        description: "TENANT Created Using Ansible"
      loop: "{{ tenantlist }}"

    - name: ENSURE TENANT VRF EXISTS
      aci_vrf:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ item.0.tenant }}"
        vrf: "{{ item.1 }}"
        description: "{{ env }} VRF Created Using Ansible"
      loop: "{{ vrflist|subelements('vrf') }}"
#
# - ADD vars from csv file
#
    - name: Read vars from csv file
      read_csv:
        path: aci_vars.csv
        key: bdz
      register: CSV_list
      tags: BDE

        
    - name: ENSURE PROD-TENANT BRIDGE DOMAIN EXISTS
      tags: BDE
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ item.value.tenantz }}"
        bd: "{{env}}-{{ item.value.bdz | default('prod_bd') }}"
        vrf: "{{ item.value.vrfz }}"
        description: "BD Created Using Ansible"
      loop: "{{ lookup('dict', CSV_list.dict) }}"
      
#   This was to help debug the DICT output # http://www.mydailytutorials.com/ansible-register-variables/
##`    - name: show loop of CSV_list
##`      debug:
##`        msg: "VRF is {{item.value.vrfz}} tenant is {{item.value.tenantz}} BD is {{item.value.bdz}}"
##`      loop: "{{ lookup('dict', CSV_list.dict)}}"
##      tags: BDE

    - name: ENSURE TENANT SUBNET EXISTS
      aci_bd_subnet:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ item.value.tenantz }}"
        bd: "{{env}}-{{ item.value.bdz | default('prod_bd') }}"
        subnet_name: "{{ item.value.bdz }}"
        gateway: "{{ item.value.gatewayz }}"
        mask: 24
        scope: "public"
        description: "Subnet Created Using Ansible"
      loop: "{{ lookup('dict', CSV_list.dict) }}"
      tags: sub