---
- name: TOP LEVEL PLAY - CREATE ACI STUFF
  hosts: apicProd
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE TENANT EXISTS
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ item.tenant }}"
        description: "TENANT Created Using Ansible"
      loop: "{{ tenantlist }}"

    - name: ENSURE TENANT VRF EXISTS
      aci_vrf:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ item.0.tenant }}"
        vrf: "{{ item.1 }}"
        description: "{{ env }} VRF Created Using Ansible"
      loop: "{{ vrflist|subelements('vrf') }}"
        
    - name: ENSURE PROD-TENANT BRIDGE DOMAIN EXISTS
      tags: BDE
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ bdlist.tenant }}"
        bd: "{{env}}-{{ item | default('prod_bd') }}"
        vrf: "{{ bdlist.vrf }}"
        description: "BD Created Using Ansible"
      loop: "{{ bdlist.bd }}"
      register: regdb

    - name: ENSURE TENANT SUBNET EXISTS
      aci_bd_subnet:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ bdlist.tenant }}"
        bd: "{{env}}-{{ item | default('prod_bd')}}"
        subnet_name: "{{ item }}"
        gateway: "10.100.{{ item.strip('DB') }}.1"
        mask: 24
        scope: "public"
        description: "Subnet Created Using Ansible"
      loop: "{{ bdlist.bd }}"
      tags: sub